#
# Copyright (c) 2015 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

spring.main.allow-bean-definition-overriding=true

### JPA / Datasource - START
spring.jpa.database=H2
spring.jpa.show-sql=false
# need to use legacy mode for now until we can upgrade EclipseLink
# (see details: https://github.com/eclipse-ee4j/eclipselink/issues/1393)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=LEGACY;
# Logging
spring.datasource.eclipselink.logging.logger=JavaLogger
spring.jpa.properties.eclipselink.logging.level=off
# Cluster aware
spring.datasource.eclipselink.query-results-cache=false
spring.datasource.eclipselink.cache.shared.default=false
# Flyway DDL
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration/
spring.flyway.sql-migration-suffixes=${spring.jpa.database}.sql
spring.flyway.table=schema_version
spring.flyway.out-of-order=true
### JPA / Datasource - END

hawkbit.default.maxAssignments=999

# Rollout Scheduler delaysy
hawkbit.rollout.end.scheduler.cron=0 0 0,12 * * *
hawkbit.rollout.scheduler.enabled=${rollout.scheduler.enabled:true}

#SNS Configuration
cosmos.server.sns.url-to-s3-transfer.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-url-to-s3-transfer-sns
cosmos.server.artifacts.s3.bucket.name=dummt-bucket
cosmos.server.sns.cdn-upload.arn=arn:aws:sns:us-east-1:800747857007:cdn-dummy-topic
cosmos.server.dd.ecu-certificates.bucket.name=dummy-bucket

# ARN for the SNS topic used for S3 file deletion
cosmos.server.sns.s3-delete.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-storage-delete-sns

cosmos.server.sns.cdn-delete.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-cdn-delete-sns