/**
 * Copyright (c) 2015 Bosch Software Innovations GmbH and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.eclipse.hawkbit.repository.jpa.tenancy;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

import java.util.Arrays;
import java.util.Collection;
import java.util.concurrent.Callable;

import org.eclipse.hawkbit.repository.exception.EntityNotFoundException;
import org.eclipse.hawkbit.repository.jpa.AbstractJpaIntegrationTest;
import org.eclipse.hawkbit.repository.model.DistributionSet;
import org.eclipse.hawkbit.repository.model.Target;
import org.eclipse.hawkbit.repository.test.util.DisposableSqlTestDatabaseExtension;
import org.eclipse.hawkbit.repository.test.util.WithSpringAuthorityRule;
import org.eclipse.hawkbit.repository.test.util.WithUser;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.data.domain.Slice;

import io.qameta.allure.Description;
import io.qameta.allure.Feature;
import io.qameta.allure.Story;

/**
 * Multi-Tenancy tests which testing the CRUD operations of entities that all
 * CRUD-Operations are tenant aware and cannot access or delete entities not
 * belonging to the current tenant.
 *
 */
@Feature("Component Tests - Repository")
@Story("Multi Tenancy")
@ExtendWith(DisposableSqlTestDatabaseExtension.class)
class MultiTenancyEntityTest extends AbstractJpaIntegrationTest {

    static final String TENANT = "aTenant";
   static final String ANOTHER_TENANT = "anotherTenant";
    Target createTargetForTenant;
    Target createTargetForAnotherTenant;
    @BeforeEach
    public void setupBeforeTest() throws Exception {

        // create targets
        createTargetForTenant = createTargetForTenant("controllerId1", "targetName1", "serialNum1", TENANT, testdataFactory.createVehicle("STLA-Brain").getId());
        createTargetForAnotherTenant = createTargetForTenant("controllerId2", "targetName2", "serialNum2", ANOTHER_TENANT, testdataFactory.createVehicle("X250").getId());


    }
    @Test
    @Description(value = "Ensures that multiple targets with same controller-ID can be created for different tenants.")
    public void createMultipleTargetsWithSameIdForDifferentTenant() throws Exception {
        // ensure both tenants see their target
        final Slice<Target> findTargetsForTenant = findTargetsForTenant(TENANT);
        assertThat(findTargetsForTenant).hasSize(1);
        assertThat(findTargetsForTenant.getContent().get(0).getTenant().toUpperCase()).isEqualTo(TENANT.toUpperCase());
        final Slice<Target> findTargetsForAnotherTenant = findTargetsForTenant(ANOTHER_TENANT);
        assertThat(findTargetsForAnotherTenant).hasSize(1);
        assertThat(findTargetsForAnotherTenant.getContent().get(0).getTenant().toUpperCase())
                .isEqualTo(ANOTHER_TENANT.toUpperCase());
    }

    @Test
    @Description(value = "Ensures that targtes created by a tenant are not visible by another tenant.")
    @WithUser(tenantId = "mytenant", allSpPermissions = true)
    public void queryTargetFromDifferentTenantIsNotVisible() throws Exception {

        // find all targets for current tenant "mytenant"
        final Slice<Target> findTargetsAll = targetManagement.findAll(PAGE);
        // no target has been created for "mytenant"
        assertThat(findTargetsAll).hasSize(0);

        // find all targets for anotherTenant
        final Slice<Target> findTargetsForTenant = findTargetsForTenant(ANOTHER_TENANT);
        // another tenant should have targets
        assertThat(findTargetsForTenant).hasSize(1);
    }

    @Test
    @Description(value = "Ensures that tenant with proper permissions can read and delete other tenants.")
    @WithUser(tenantId = "mytenant", allSpPermissions = true)
    public void deleteAnotherTenantPossible() throws Exception {
        // create target for another tenant
        assertThat(systemManagement.findTenants(PAGE)).as("Expected number if tenants before deletion is").hasSize(4);

        systemManagement.deleteTenant(ANOTHER_TENANT);

        assertThat(systemManagement.findTenants(PAGE)).as("Expected number if tenants after deletion is").hasSize(3);
    }

    @Test
    @Description(value = "Ensures that tenant metadata is retrieved for the current tenant.")
    @WithUser(tenantId = "mytenant", autoCreateTenant = false, allSpPermissions = true)
    public void getTenanatMetdata() throws Exception {

        // autogenerated
        assertThat(distributionSetTypeManagement.findAll(PAGE)).isEmpty();
        assertThat(systemManagement.getTenantMetadata().getTenant().toUpperCase()).isEqualTo("mytenant".toUpperCase());
        assertThat(distributionSetTypeManagement.findAll(PAGE)).isNotEmpty();

        // check that the cache is not getting in the way, i.e. "bumlux" results
        // in bumlux and not
        // mytenant
        assertThat(WithSpringAuthorityRule.runAs(WithSpringAuthorityRule.withUserAndTenant("user", "bumlux"),
                () -> systemManagement.getTenantMetadata().getTenant().toUpperCase()))
                        .isEqualTo("bumlux".toUpperCase());
    }

    @Test
    @Description(value = "Ensures that targets created from a different tenant cannot be deleted from other tenants")
    @WithUser(tenantId = "mytenant", allSpPermissions = true)
    public void deleteTargetFromOtherTenantIsNotPossible() throws Exception {
        // create target for another tenant
        // ensure target cannot be deleted by 'mytenant'
        try {
            targetManagement.delete(Arrays.asList(createTargetForAnotherTenant.getId()));
            fail("mytenant should not have been able to delete target of anotherTenant");
        } catch (final EntityNotFoundException ex) {
            // ok
        }

        Slice<Target> targetsForAnotherTenant = findTargetsForTenant(ANOTHER_TENANT);
        assertThat(targetsForAnotherTenant).hasSize(1);

        // ensure another tenant can delete the target
        deleteTargetsForTenant(ANOTHER_TENANT, Arrays.asList(createTargetForAnotherTenant.getId()));
        targetsForAnotherTenant = findTargetsForTenant(ANOTHER_TENANT);
        assertThat(targetsForAnotherTenant).hasSize(0);
    }

    @Test
    @Description(value = "Ensures that multiple distribution sets with same name and version can be created for different tenants.")
    public void createMultipleDistributionSetsWithSameNameForDifferentTenants() throws Exception {

        // known tenant names
        createDistributionSetForTenant(TENANT);
        createDistributionSetForTenant(ANOTHER_TENANT);

        // ensure both tenants see their distribution sets
        final Slice<DistributionSet> findDistributionSetsForTenant = findDistributionSetForTenant(TENANT);
        assertThat(findDistributionSetsForTenant).hasSize(1);
        assertThat(findDistributionSetsForTenant.getContent().get(0).getTenant().toUpperCase())
                .isEqualTo(TENANT.toUpperCase());
        final Slice<DistributionSet> findDistributionSetsForAnotherTenant = findDistributionSetForTenant(ANOTHER_TENANT);
        assertThat(findDistributionSetsForAnotherTenant).hasSize(1);
        assertThat(findDistributionSetsForAnotherTenant.getContent().get(0).getTenant().toUpperCase())
                .isEqualTo(ANOTHER_TENANT.toUpperCase());
    }

    private <T> T runAsTenant(final String tenant, final Callable<T> callable) throws Exception {
        return WithSpringAuthorityRule.runAs(WithSpringAuthorityRule.withUserAndTenant("user", tenant), callable);
    }

    private Target createTargetForTenant(final String controllerId, final String tenant) throws Exception {
        return runAsTenant(tenant, () -> testdataFactory.createTarget(controllerId));
    }

    private Target createTargetForTenant(final String controllerId, final String targetName, final String serialNumber,
                                         final String tenant, Long vehicleModelId) throws Exception {
        return runAsTenant(tenant, () -> testdataFactory.createTarget(controllerId, targetName, serialNumber, vehicleModelId));
    }

    private Slice<Target> findTargetsForTenant(final String tenant) throws Exception {
        return runAsTenant(tenant, () -> targetManagement.findAll(PAGE));
    }

    private void deleteTargetsForTenant(final String tenant, final Collection<Long> targetIds) throws Exception {
        runAsTenant(tenant, () -> {
            targetManagement.delete(targetIds);
            return null;
        });
    }

    private DistributionSet createDistributionSetForTenant(final String tenant) throws Exception {
        return runAsTenant(tenant, testdataFactory::createDistributionSet);
    }

    private Slice<DistributionSet> findDistributionSetForTenant(final String tenant) throws Exception {
        return runAsTenant(tenant, () -> distributionSetManagement.findByCompleted(PAGE, true));
    }
}
