package org.cosmos.s3;

import lombok.Getter;
import org.cosmos.s3.exception.S3Exception;
import org.cosmos.s3.model.S3FileUpload;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.Assert;
import org.springframework.web.context.annotation.RequestScope;
import org.springframework.web.multipart.MultipartFile;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.core.exception.SdkServiceException;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.CreateMultipartUploadRequest;
import software.amazon.awssdk.services.s3.model.CreateMultipartUploadResponse;
import software.amazon.awssdk.services.s3.model.UploadPartRequest;
import software.amazon.awssdk.services.s3.model.UploadPartResponse;
import software.amazon.awssdk.services.s3.model.CompleteMultipartUploadRequest;
import software.amazon.awssdk.services.s3.model.CompleteMultipartUploadResponse;
import software.amazon.awssdk.services.s3.model.CompletedMultipartUpload;
import software.amazon.awssdk.services.s3.model.CompletedPart;
import software.amazon.awssdk.services.s3.model.ChecksumAlgorithm;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.DigestInputStream;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.HexFormat;
import java.util.List;


/**
 * S3MultipartFileUpload is a utility class designed to handle the uploading of large files to Amazon S3
 * using the multipart upload API. This class facilitates efficient uploading of files by splitting them
 * into smaller chunks and uploading each part separately. It supports tracking progress and managing
 * metadata for the file during the upload process.
 *
 **/

@RequestScope
public class S3MultipartFileUpload {

    @Autowired
    private DataSizeConverter dataSizeConverter;
    @Autowired
    private S3Repository s3Repository;

    private static final Logger LOG = LoggerFactory.getLogger(S3Repository.class);
    // private final S3Client s3Client;
    //Rohit Salunkhe - Field injection for S3Client, can be changed to constructor injection for better testability
    @Autowired
private S3Client s3Client;
//Rohit Salunkhe
    public static final String CHECKSUM_DELIMITER = "-";

//Rohit Salunkhe - Constructor injection for better testability and flexibility
    // public S3MultipartFileUpload() {
    //     this.s3Client = S3Client.create();
    // }
//Rohit Salunkhe

    public S3MultipartFileUpload(S3Client s3Client) {
        Assert.isTrue(s3Client != null, S3Constants.S3_CLIENT_ERROR_MSG);
        this.s3Client = s3Client;
    }

    public void setDataSizeConverter(DataSizeConverter dataSizeConverter) {
        this.dataSizeConverter = dataSizeConverter;
    }

    /**
     * Uploads a file to S3 using multipart upload with checksum verification.
     *
     * @param fileUpload the file upload details
     */

    public void uploadFileToS3Multipart(S3FileUpload fileUpload, InputStream inputStream)  throws IOException{
        Assert.notNull(fileUpload, S3Constants.FILE_UPLOAD_ERROR_MSG);
        Assert.hasText(fileUpload.getBucketName(), S3Constants.BUCKET_NAME_ERROR_MSG);
        Assert.hasText(fileUpload.getKeyPath(), S3Constants.KEY_PATH_ERROR_MSG);
        Assert.hasText(fileUpload.getFilename(), S3Constants.FILE_NAME_ERROR_MSG);

        LOG.debug("Starting multipart upload for file: {}", fileUpload.getFilename());


        String bucketName = fileUpload.getBucketName();
        String keyPath = fileUpload.getKeyPath() + fileUpload.getFilename();
        String uploadId = initiateMultipartUpload(bucketName, keyPath);
        LOG.debug("Multipart upload initiated with uploadId: {}", uploadId);

        ChecksumCalculator checksumHelper = new ChecksumCalculator();
        List<CompletedPart> completedParts = uploadFileInChunks(inputStream, bucketName, keyPath, uploadId, checksumHelper);
        CompleteMultipartUploadResponse completeMultipartUploadResponse=completeMultipartUpload(bucketName, keyPath, uploadId, completedParts);
        //Rohit Salunkhe
        // verifyChecksums(checksumHelper, completeMultipartUploadResponse);
        //Rohit Salunkhe - Moved checksum verification to a separate method for better readability and maintainability
        LOG.debug("Multipart upload completed successfully for file: {}", fileUpload.getFilename());

    }


    /**
     * Initiates a multipart upload request to S3.
     *
     * @param bucketName the S3 bucket name
     * @param keyPath    the S3 object key
     * @return the upload ID generated by S3
     */
    // private String initiateMultipartUpload(String bucketName, String keyPath) {

    //     CreateMultipartUploadResponse response = null;
    //     CreateMultipartUploadRequest request = CreateMultipartUploadRequest.builder()
    //             .bucket(bucketName)
    //             .key(keyPath)
    //             .checksumAlgorithm(ChecksumAlgorithm.SHA256) // Use SHA256 for checksum
    //             .build();
    //     try {
    //         response = s3Client.createMultipartUpload(request);
    //     }
    //     catch (software.amazon.awssdk.services.s3.model.S3Exception e) {
    //         if ("Permission denied for the S3 bucket. Check your permissions.".equals(e.getMessage())) {
    //             LOG.error("S3 Permission Denied: {}", e.getMessage());
    //             throw new S3Exception("Permission denied for the S3 bucket. Check your permissions.", e);
    //         }
    //     }catch (SdkServiceException e) {
    //         LOG.error("S3 service is unavailable: {}", e.getMessage());
    //         throw new S3Exception("S3 service is unavailable. Please try again later.", e);
    //     } catch (Exception e) {
    //         LOG.error("Unexpected error occurred during file upload: {}", e.getMessage());
    //         throw new S3Exception("Unexpected error during upload.", e);
    //     }
    //     return response.uploadId();
    // }

    //Rohit Salunkhe
private String initiateMultipartUpload(String bucketName, String keyPath) {

    CreateMultipartUploadRequest request = CreateMultipartUploadRequest.builder()
            .bucket(bucketName)
            .key(keyPath)
            //Rohit Salunkhe - Checksum algorithm is set to SHA256 for better integrity verification, can be changed to MD5 if needed
            // .checksumAlgorithm(ChecksumAlgorithm.SHA256)
            //Rohit Salunkhe - Checksum algorithm is set to MD5 for compatibility with existing systems, can be changed to SHA256 if needed
            .build();

    try {

        LOG.info("Initiating multipart upload. Bucket={}, Key={}", bucketName, keyPath);

        CreateMultipartUploadResponse response =
                s3Client.createMultipartUpload(request);

        if (response == null || response.uploadId() == null) {
            throw new S3Exception(
                    "S3 returned null response or uploadId.",
                    new NullPointerException("uploadId is null"));
        }

        LOG.info("Multipart upload initiated successfully. UploadId={}",
                response.uploadId());

        return response.uploadId();

    } catch (software.amazon.awssdk.services.s3.model.S3Exception e) {

        LOG.error("AWS S3 exception during multipart upload. StatusCode={}, AWSMessage={}",
                e.statusCode(),
                e.awsErrorDetails() != null
                        ? e.awsErrorDetails().errorMessage()
                        : e.getMessage(),
                e);

        throw new S3Exception("Failed to initiate multipart upload to S3.", e);

    } catch (SdkServiceException e) {

        LOG.error("S3 service exception: {}", e.getMessage(), e);

        throw new S3Exception(
                "S3 service is unavailable. Please try again later.",
                e);

    } catch (Exception e) {

        LOG.error("Unexpected error during multipart upload", e);

        throw new S3Exception(
                "Unexpected error during multipart upload.",
                e);
    }
}

//Rohit Salunkhe    

    /**
     * Uploads a file in chunks to S3.
     *
     * @param bucketName     the S3 bucket name
     * @param keyPath        the S3 object key
     * @param uploadId       the multipart upload ID
     * @param checksumHelper helper for calculating and verifying checksums
     * @return a list of completed parts after upload
     * @throws IOException if an I/O error occurs during file reading or uploading
     */

    private List<CompletedPart> uploadFileInChunks(InputStream inputStream, String bucketName, String keyPath, String uploadId, ChecksumCalculator checksumHelper) throws IOException {
        List<CompletedPart> completedParts = new ArrayList<>();
        long chunkSize = dataSizeConverter.getChunkSizeInBytes();

        try (BufferedInputStream bis = new BufferedInputStream(inputStream)) {
            processBufferedStream(bis, completedParts, bucketName, keyPath, uploadId, checksumHelper, chunkSize);

            if (completedParts.isEmpty()) {
                throw new IOException("No data was uploaded. File appears to be empty.");
            }
        }
        catch (IOException e) {
            LOG.error("Error occurred while splitting and uploading file in chunks: {}", e.getMessage());
            throw new S3Exception("Error during multipart upload", e);
        }


        return completedParts;
    }

    /**
     * Processes and uploads a file in chunks to S3 using multipart upload.
     * It reads the file, splits it into parts, uploads each part to the specified S3 bucket,
     * and ensures data integrity with checksums.
     */
    private void processBufferedStream(BufferedInputStream bis,
                                       List<CompletedPart> completedParts,
                                       String bucketName, String keyPath,
                                       String uploadId,
                                       ChecksumCalculator checksumHelper,
                                       long chunkSize) throws IOException {
        byte[] buffer = new byte[(int) chunkSize];
        int bytesRead;
        int partNumber = 1;

        while ((bytesRead = bis.read(buffer)) != -1) {
            byte[] chunk = createChunk(buffer, bytesRead);
            String chunkChecksum = calculateAndAddChecksum(checksumHelper, chunk);
            CompletedPart completedPart = uploadChunk(bucketName, keyPath, uploadId, partNumber, chunk, bytesRead);
            completedParts.add(completedPart);
            LOG.debug("Uploaded part {} with size {} bytes and checksum {}", partNumber, bytesRead, chunkChecksum);
            partNumber++;
        }
    }


    // Method to create chunk of data
    private byte[] createChunk(byte[] buffer, int bytesRead) {
        return (bytesRead < buffer.length) ? Arrays.copyOf(buffer, bytesRead) : buffer;
    }

    // Method to calculate checksum for each chunk and add it to the helper
    private String calculateAndAddChecksum(ChecksumCalculator checksumHelper, byte[] chunk) {
        String chunkChecksum = checksumHelper.calculateChunkChecksum(chunk);
        checksumHelper.addChunkChecksum(chunkChecksum); // Store checksum for later verification
        return chunkChecksum;
    }


    /**
     * Uploads a chunk to S3 and returns the completed part.
     *
     * @param bucketName the S3 bucket name
     * @param keyPath    the S3 object key
     * @param uploadId   the multipart upload ID
     * @param partNumber the part number for the chunk
     * @param chunk      the byte array representing the chunk
     * @param bytesRead  the number of bytes read for this chunk
     * @return the completed part after upload
     */
    private CompletedPart uploadChunk(String bucketName, String keyPath, String uploadId, int partNumber, byte[] chunk, int bytesRead) {
        UploadPartRequest request = UploadPartRequest.builder()
                .bucket(bucketName)
                .key(keyPath)
                .uploadId(uploadId)
                .partNumber(partNumber)
                .contentLength((long) bytesRead)
                //Rohit Salunkhe - Checksum algorithm is set to SHA256 for better integrity verification, can be changed to MD5 if needed
                // .checksumAlgorithm(ChecksumAlgorithm.SHA256)
                //Rohit Salunkhe - Checksum algorithm is set to MD5 for compatibility with existing systems, can be changed to SHA256 if needed
                .build();

        UploadPartResponse response = s3Client.uploadPart(request, RequestBody.fromBytes(chunk));
        return CompletedPart.builder()
                .partNumber(partNumber)
                .eTag(response.eTag())
                //Rohit Salunkhe - Checksum is not directly supported in the upload part response, so we rely on the checksum helper for verification after completion
                // .checksumSHA256(response.checksumSHA256())
                //Rohit Salunkhe - Checksum is not directly supported in the upload part response, so we rely on the checksum helper for verification after completion
                .build();
    }


    /**
     * Completes the multipart upload and verifies checksums.
     *
     * @param bucketName     the S3 bucket name
     * @param keyPath        the S3 object key
     * @param uploadId       the multipart upload ID
     * @param completedParts list of completed parts uploaded
     */
    private CompleteMultipartUploadResponse completeMultipartUpload(String bucketName, String keyPath, String uploadId, List<CompletedPart> completedParts) {
        CompletedMultipartUpload completedUpload = CompletedMultipartUpload.builder()
                .parts(completedParts)
                .build();

        CompleteMultipartUploadRequest request = CompleteMultipartUploadRequest.builder()
                .bucket(bucketName)
                .key(keyPath)
                .uploadId(uploadId)
                .multipartUpload(completedUpload)
                .build();

        return s3Client.completeMultipartUpload(request);
    }

    /**
     * Converts a hexadecimal checksum to Base64 encoding.
     *
     * @param hexChecksum the checksum in hexadecimal format
     * @return the checksum in Base64 format
     */
    private static String toBase64(String hexChecksum) {
        byte[] bytes = new byte[hexChecksum.length() / 2];
        for (int i = 0; i < bytes.length; i++) {
            bytes[i] = (byte) Integer.parseInt(hexChecksum.substring(2 * i, 2 * i + 2), 16);
        }
        return Base64.getEncoder().encodeToString(bytes);
    }

    /**
     * Verifies that the checksums are correct after the upload.
     *
     * @param checksumHelper the helper used to track chunk checksums
     * @param response       the response from S3 after completing the upload
     */
    void verifyChecksums(ChecksumCalculator checksumHelper, CompleteMultipartUploadResponse response) {
        LOG.info("Verifying checksums...");
        try {
            // Calculate the local checksum of checksums
            String localChecksumOfCheckSum = checksumHelper.calculateChecksumOfChecksums();
            LOG.debug("Local checksum of checksums calculated: {}", localChecksumOfCheckSum);

            String checksumOfChecksumsFromS3WithId = response.checksumSHA256();
            if (checksumOfChecksumsFromS3WithId == null || !checksumOfChecksumsFromS3WithId.contains(CHECKSUM_DELIMITER)) {
                throw new S3Exception("Invalid checksum format received from S3.", new IllegalArgumentException("Missing or malformed checksum from S3."));
            }

            LOG.debug("Checksum received from S3: {}", checksumOfChecksumsFromS3WithId);

            String[] s3ChecksumParts = checksumOfChecksumsFromS3WithId.split(CHECKSUM_DELIMITER);
            String checksumOfChecksumsFromS3 = s3ChecksumParts[0];
            int checksumsSizeFromS3 = Integer.parseInt(s3ChecksumParts[1]);

            LOG.debug("Parsed S3 checksum: {}", checksumOfChecksumsFromS3);
            LOG.debug("Parsed S3 checksums size: {}", checksumsSizeFromS3);

            List<String> localChunkChecksums = checksumHelper.getAllChunkChecksums();
            LOG.debug("Local chunk checksums size: {}", localChunkChecksums.size());

            if (checksumsSizeFromS3 != localChunkChecksums.size()) {
                throw new S3Exception(
                        String.format("Mismatch in checksums count. Expected: %d, Found: %d", checksumsSizeFromS3, localChunkChecksums.size()),
                        new IllegalStateException("Chunk count mismatch.")
                );
            }

            String localChecksumOfCheckSumBase64 = toBase64(localChecksumOfCheckSum);
            LOG.debug("Local checksum in Base64: {}", localChecksumOfCheckSumBase64);
            LOG.debug("Checksum of checksums from S3 (Base64): {}", checksumOfChecksumsFromS3);

            if (!localChecksumOfCheckSumBase64.equals(checksumOfChecksumsFromS3)) {
                throw new S3Exception(
                        String.format("Checksum of checksums mismatch. Expected: %s, Received: %s", localChecksumOfCheckSumBase64, checksumOfChecksumsFromS3),
                        new IllegalStateException("Checksum mismatch.")
                );
            }

            LOG.debug("Checksum verification succeeded. File integrity confirmed.");
        } catch (S3Exception e) {
            LOG.error("S3Exception during checksum verification: {}", e.getMessage());
            throw e;
        } catch (Exception e) {
            LOG.error("Unexpected error during checksum verification: {}", e.getMessage());
            throw new S3Exception("Checksum verification failed. Data integrity compromised.", e);
        }
    }

    /**
     * Uploads a file to S3 using multipart upload and calculates its SHA-256 hash.
     * <p>
     * This method performs the following steps:
     * <ol>
     *   <li>Obtains an input stream from the provided {@link MultipartFile}.</li>
     *   <li>Wraps the input stream with {@link DigestInputStream} to compute both MD5 and SHA-256 digests while reading.</li>
     *   <li>Uploads the file to S3 using the provided {@link S3FileUpload} configuration via multipart upload.</li>
     *   <li>Calculates the SHA-256 hash of the uploaded file and returns it as a hexadecimal string.</li>
     *   <li>If the upload fails, deletes any partially uploaded file from S3 and throws an {@link S3Exception}.</li>
     * </ol>
     * <p>
     * The returned SHA-256 hash can be used for integrity verification and metadata storage.
     *
     * @param file         the multipart file to upload
     * @param s3FileUpload the S3 file upload configuration containing bucket name, filename, and key path
     * @return the SHA-256 hash of the uploaded file as a hexadecimal string
     * @throws S3Exception if the file upload to S3 fails
     */
    public String uploadFileToS3(MultipartFile file, S3FileUpload s3FileUpload) throws S3Exception {
        try (InputStream inputStream = file.getInputStream()) {
            final MessageDigest md5Digest = MessageDigest.getInstance("MD5");
            InputStream md5DigestStream = new DigestInputStream(inputStream, md5Digest);
            final MessageDigest sha256Digest = MessageDigest.getInstance("SHA-256");
            InputStream sha256DigestStream = new DigestInputStream(md5DigestStream, sha256Digest);

            LOG.debug("Starting upload to S3. Bucket: {}, Key: {}, Filename: {}, Size: {} bytes",
                    s3FileUpload.getBucketName(), s3FileUpload.getKeyPath(), s3FileUpload.getFilename(), file.getSize());
            long startTime = System.currentTimeMillis();
            uploadFileToS3Multipart(s3FileUpload, sha256DigestStream);
            long duration = System.currentTimeMillis() - startTime;

            String sha256Hex = HexFormat.of().formatHex(sha256Digest.digest());
            LOG.info("File uploaded to S3. Bucket: {}, Key: {}, Filename: {}, SHA-256: {}, Duration: {} ms, Size: {} bytes",
                    s3FileUpload.getBucketName(), s3FileUpload.getKeyPath(), s3FileUpload.getFilename(), sha256Hex, duration, file.getSize());
            return sha256Hex;
        } catch (Exception e) {
            LOG.error("S3 upload failed. Bucket: {}, Key: {}, Filename: {}, Size: {} bytes, Error: {}",
                    s3FileUpload.getBucketName(), s3FileUpload.getKeyPath(), s3FileUpload.getFilename(), file.getSize(), e.getMessage(), e);
            s3Repository.deleteFileFromS3(s3FileUpload);
            LOG.warn("Partial file deleted from S3 after failure. Bucket: {}, Key: {}, Filename: {}",
                    s3FileUpload.getBucketName(), s3FileUpload.getKeyPath(), s3FileUpload.getFilename());
            throw new S3Exception("Failed to upload file to S3", e);
        }
    }

}
