#Swagger Configuration
spring.mvc.pathmatch.matching-strategy = ant_path_matcher
spring.jackson.serialization.indent_output = true

swagger.doc.device.version = ${rest.doc.device.version:0}
swagger.doc.management.version = ${rest.doc.management.version:0}
swagger.doc.system.version = ${rest.doc.system.version:0}

## Swagger Security
swagger.doc.security.oidc.token-uri=${spring.security.oauth2.client.provider.oidc.token-uri:}
swagger.doc.security.oidc.scope=${spring.security.oauth2.client.registration.oidc.scope:}

springdoc.swagger-ui.doc-expansion=none
