-- 1. Table: sp_erc_structure
CREATE TABLE IF NOT EXISTS sp_erc_structure
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    erc_type CHARACTER VARYING(10) NOT NULL,
    erc_format CHARACTER VARYING(256) NOT NULL,
    created_at BIGINT,
    created_by CHARACTER VARYING(64),
    updated_at BIGINT,
    updated_by CHARACTER VARYING(64),
    optlock_revision BIGINT,
    CONSTRAINT uq_sp_erc_structure_type UNIQUE (erc_type)
);

-- 2. Table: sp_erc_update_phase
CREATE TABLE IF NOT EXISTS sp_erc_update_phase
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    erc_type CHARACTER VARYING(10) NOT NULL,
    code CHARACTER VARYING(10) NOT NULL,
    device_state_offboard CHARACTER VARYING(256),
    message_text CHARACTER VARYING(500),
    created_at BIGINT,
    created_by CHARACTER VARYING(64),
    updated_at BIGINT,
    updated_by CHARACTER VARYING(64),
    optlock_revision BIGINT,
    CONSTRAINT fk_sp_erc_update_phase_erc_type
        FOREIGN KEY (erc_type)
        REFERENCES sp_erc_structure (erc_type)
        ON DELETE CASCADE,
    CONSTRAINT uq_sp_erc_update_phase_type_code UNIQUE (erc_type, code)
);

-- 3. Table: sp_erc_code
CREATE TABLE IF NOT EXISTS sp_erc_code
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    erc_type CHARACTER VARYING(10) NOT NULL,
    code CHARACTER VARYING(10) NOT NULL,
    device_state_offboard CHARACTER VARYING(256),
    message_text CHARACTER VARYING(500),
    created_at BIGINT,
    created_by CHARACTER VARYING(64),
    updated_at BIGINT,
    updated_by CHARACTER VARYING(64),
    optlock_revision BIGINT,
    CONSTRAINT fk_sp_erc_code_erc_type
        FOREIGN KEY (erc_type)
        REFERENCES sp_erc_structure (erc_type)
        ON DELETE CASCADE,
    CONSTRAINT uq_sp_erc_code_type_code UNIQUE (erc_type, code)
);