#
# Copyright (c) 2015 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

management.endpoints.web.exposure.include=*
# Sandbox, small files only
spring.servlet.multipart.max-file-size=100000000
spring.servlet.multipart.max-request-size=100000000
hawkbit.server.security.dos.maxArtifactSize=100000000
hawkbit.server.security.dos.maxArtifactStorage=100000000000
spring.servlet.multipart.enabled=true
# User Security
spring.security.user.name=admin
spring.security.user.password={noop}admin
spring.main.allow-bean-definition-overriding=true
# Http Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# DDI authentication configuration
hawkbit.server.ddi.security.authentication.anonymous.enabled=true
hawkbit.server.ddi.security.authentication.targettoken.enabled=true
hawkbit.server.ddi.security.authentication.gatewaytoken.enabled=true
hawkbit.server.ddi.security.createTargetOnRun=false
# Optional events
hawkbit.server.repository.publish-target-poll-event=false
# Define own users instead of default "admin" user:
#hawkbit.server.im.users[0].username=hawkbit
#hawkbit.server.im.users[0].password={noop}isAwesome!
#hawkbit.server.im.users[0].firstname=Eclipse
#hawkbit.server.im.users[0].lastname=HawkBit
#hawkbit.server.im.users[0].permissions=ALL
# Enable CORS and specify the allowed origins:
#hawkbit.server.security.cors.enabled=true
#hawkbit.server.security.cors.allowedOrigins=http://localhost
# Swagger Documentation
rest.doc.device.version=@project.version@
rest.doc.management.version=@project.version@
rest.doc.system.version=@project.version@
# OIDC configurations
spring.security.oauth2.client.registration.oidc.client-id=MUWABNBDNBCKBAXEQPYRQNFCECFPKVWD
spring.security.oauth2.client.registration.oidc.client-secret=q7J2micFGjk5EFto2bp1cHd0Cly0ZyzMefJ9fLU3sKpzTR3vmEOm3A6ZkOANWIfH
spring.security.oauth2.client.registration.oidc.scope=openid,prd:aug,profile
spring.security.oauth2.client.registration.oidc.env=local
# OAUTH2 Provider
spring.security.oauth2.client.provider.oidc.type=custom
spring.security.oauth2.client.provider.oidc.authorized-clients[0]=MUWABNBDNBCKBAXEQPYRQNFCECFPKVWD
spring.security.oauth2.client.provider.oidc.authorized-clients[1]=CCRSKDQDBZDZLLSZYUWMYDWECWHDQX
spring.security.oauth2.client.provider.oidc.issuer-uri=https://idfed-preprod.mpsa.com:443
spring.security.oauth2.client.provider.oidc.authorization-uri=https://idfed-preprod.mpsa.com:443/as/authorization.oauth2
spring.security.oauth2.client.provider.oidc.token-uri=https://idfed-preprod.mpsa.com:443/as/token.oauth2
spring.security.oauth2.client.provider.oidc.user-info-uri=https://idfed-preprod.mpsa.com:443/idp/userinfo.openid
spring.security.oauth2.client.provider.oidc.jwk-set-uri=https://idfed-preprod.mpsa.com:443/pf/JWKS
spring.security.oauth2.client.provider.oidc.logout-uri=https://idfed-preprod.mpsa.com/idp/startSLO.ping
# Spring cloud configurations
spring.cloud.config.enabled=false
#Create Rollout default log parameters
log.collectionRequired=false
log.maxSuccessVin=20
log.maxFailureVin=100
log.maxLogAllFileSize=1048576
log.maxLogEachFileSize=209715
log.maxNumberOfFiles=5
#DDI Inventory Signature Public Key
#Need to remove once the implementation changes.
hawkbit.server.ddi.inventory.public-key=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEntWbbWxaHPMztOatFDr3A+FGJQxcDK2YqO9bQlTznj2MqJdklzRpoBt4RnC7euskCJqnf7r7xUQB1qRLdIw+hA==
hawkbit.server.ddi.inventory.signing-Algorithm=SHA256withECDSA

# Akamai CDN Configuration
cdn.akamai.host=stellantis-ota.ssh.upload.akamai.com
cdn.akamai.port=22
cdn.akamai.user=sshacs
cdn.akamai.keyfile=-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: DES-EDE3-CBC,07428FC5491C5A16\n\nuMMJXJFkF6iMlw+/K4m+rP2hGLy7lv2KGW78zunbdzYVr3UaoWKZc3A1/dV8/z/b4sKcDqmjdQacmREk4e5Wu1MCMad2muIoGFLFg9/gcwbjMKnma/ml9WyHAuyuzIH8iHNyos2uEhAPdkbJFARgUCdvZ0zh7jOfIOdkJXpZgpFIR5VoT4GBoZSy97EUw9ADabTS6+tM0uJkCXjbL0KMIZXBJn//f676OTslRdH/3y7aVP+yEzkcwiwLQpg0ROwzjTT1u0Q8BV8dq4OVVXGuRoJ5DJfcg5xXX4ToNkSGQuCjOhgWwYXeYLYTwJ8EXpogOxeXyqWbSN29UNAxwoQLB6Hoz+etK3ybAJ3FKwfgX0AsmIVO3FBkjgbCTT1sXwktxFC8sHHaEDqKkgIHalXBOMkk7Cq/fXWy59HswPYmGNU6+geliWYyFnwQSdVDMumI2YemB5WkCyhLbF7BMnHfxkPNzYjzkqcg4obzWqCM5RwHGEVhc/ny4yOPHKaQH+xUqhqv8ssXG0MoB2MwGBNYUNlfUNw49nnjxSxXE9jvRIxN/SAgzJUclRhakyXgnUWDDdGYplVqXE8P/ferRfPYdoipAJqh0WSmCB801wlr+SjFVGQNdOc711cfSirOdIwnMWnekAwbc3OLLwVdUHM2b0PoZc0JQpU79XjVUPbf2NCTdjTVkYKB9vE9q9WytJXPW5WlmFv8u2zn/DmXb8j1MUCPhacrbH8bPf17xRGP0bHSZlqv/vsh1XYuzj25K/ky/yxJ2ZAUmNMsfBh03/eNRdWO++1ujzggRGJFNK2xgCCldbU6biERvyvjnE61FY3LCRljh0aAVUGLdvEtD7UcYlVRpyZUTzvjhIA52G7YVPvG7TKoWrJ4LwUxsmHkTuImF3evgViuvamOgYxF61RhCk9TFqkUjBpC8D2kRUVcf25t9n14HDSWZQttDhFH5+wZ6lNada8pf0AsSXEfZEpFrYNkUAvtipCPbnqLVktncwmD069s4UkH8zSvj7s4CP2eI2mNjP70hgsmqCU6BZ3NvtsHdojebxzIvVSi541ReJFsfNWPR1YK7foCKPednU+2M8GwjCCmyKpdRmXvGq6mvu012Y0VoifEZyqWv9u2tm5ftC6iCSOc+uowzmp73vytArlCiTkRMWITatbeD/OV6PzNMn6011uJjUkzH9PbZoXNAIj2PUxTojyS9xLzJfXLqyFrqCYT3XqAaHkiR2cPxHTWxmyiHcvgp2NSXqTGen6T5CcZR4sZBNY1f1zSY8uLlgxHTY0lQyH2vJZs1oEJjgk6db8YsAsbn01mP+AI+pTQ2f1g443ODwbqyEIQVfb/VglNSHi2K9Oa6pG7yU/GFsOeZcLEvp4uy1ZITPcSnKr4IwsRSZlrjmHpC4eWP1OGmxPFHrXL7U7Ud6+G2let1XDGzydmFLHFODzBBHCH+6fYFLgAuLKQmsmuZCm5QkiRh/1I57aoopCKZMpcop/tEW8Rxa09zkKB9SUAN5eJWeDLBI9SNYuH8IXp8RroveS3NpM2OobBHDYc6LyfW3E6R1yhRSwMkxCuHYXU/5xEi/CcY5CD9lXc+g==\n-----END RSA PRIVATE KEY-----
cdn.akamai.passphrase=cosmos
cdn.akamai.directory=1624091
hawkbit.artifact.url.cdn.host=http://testcdn.cosmos.stellantis.edgekey.net
hawkbit.artifact.validate-file-size=false
hawkbit.artifact.url.cdn.rootDirectory=/dev
# ESP RSP file configuration
org.cosmos.file.support-package.file.path=./app/dev/support-package/{spType}/sha256
org.cosmos.file.support-package.file.size=1KB


#PKI PrivateKey path
#Environment Specific:Needs update once available
cosmos.server.pki.internal.dd.private.keyPath=/CERTIFICATES/INTERNAL/DEV/DD/PRIVATEKEY

management.endpoints.jmx.exposure.include=info,loggers

# Rollout Scheduler
rollout.scheduler.enabled=true

#SNS Configuration
cosmos.server.sns.url-to-s3-transfer.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-url-to-storage-transfer-sns
cosmos.server.artifacts.s3.bucket.name=cosmos-us-east-1-dev-artifacts
cosmos.server.s3.support-package.bucket.name=cosmos-us-east-1-dev-support-packages
cosmos.server.sns.cdn-upload.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-storage-to-cdn-upload-sns
cosmos.server.sns.cdn-delete.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-cdn-delete-sns
initConfig.softwareModuleFormat=QNX,Android,Linux,Vera,Machina
# ARN for the SNS topic used for S3 file deletion
cosmos.server.sns.s3-delete.arn=arn:aws:sns:us-east-1:800747857657:cosmos-dev-storage-delete-sns
cosmos-file-transfer-success-server-sqs.name=cosmos-dev-file-transfer-success-server-sqs
cosmos-file-transfer-failure-server-sqs.name=cosmos-dev-file-transfer-failure-server-sqs
cosmos-file-delete-success-server-sqs.name=cosmos-dev-file-delete-success-sqs
cosmos-file-delete-failure-server-sqs.name=cosmos-dev-file-delete-failure-sqs
rollout.valid.end.date.days=2

#S3 bucket used for fetching ECU Certificates
cosmos.server.dd.ecu-certificates.bucket.name=cosmos-offboard-ecu-certs-int-2
cosmos.server.dd.ecu-certificates.issuer.name=stla_otateam_test_pki_ds_subca_g1

#TTL configuration for cache
cosmos.server.dd.signature-cache-randomization-window-days=30

#Valkey cache configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.enabled=false

# Default properties
cosmos.server.artifacts.purged.vins.batch.size=200

# Kafka settings.
external.services.kafka-service.baseurl=http://localhost:8080
cosmos.server.kafka.retryMaxAttempt=1
cosmos.server.kafka.retryDelay=2000
cosmos.server.kafka.retryMultiplier=2
# Kafka topics for COSMOS
cosmos.server.kafka.rollout-status-topic=rollout.status
cosmos.server.kafka.rollout-vehicle-status-topic=rollout.vehicle.status
cosmos.server.kafka.vehicle-inventory-topic=vehicle.inventory
cosmos.server.kafka.package-status-topic=package.status
cosmos.server.kafka.vehicle-general-topic=vehicle.general
spring.jpa.database=POSTGRESQL