#DDI Inventory Signature Public Key
#Need to remove once the implementation changes.
hawkbit.server.ddi.inventory.public-key=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEntWbbWxaHPMztOatFDr3A+FGJQxcDK2YqO9bQlTznj2MqJdklzRpoBt4RnC7euskCJqnf7r7xUQB1qRLdIw+hA==
hawkbit.server.ddi.inventory.signing-Algorithm=SHA256withECDSA
rollout.valid.end.date.days=2