#
# Copyright (c) 2015 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

# API getting exposed with spring actuator
management.endpoints.web.exposure.include=*

# For production large files support
spring.servlet.multipart.max-file-size=1073741824
spring.servlet.multipart.max-request-size=1073741824
hawkbit.server.security.dos.maxArtifactSize=1073741824
hawkbit.server.security.dos.maxArtifactStorage=107374182400
spring.servlet.multipart.enabled=true

# Swagger Documentation
rest.doc.device.version=@project.version@
rest.doc.management.version=@project.version@
rest.doc.system.version=@project.version@

# User Security
server.port=8080
spring.security.user.name=admin
spring.security.user.password={noop}admin
spring.main.allow-bean-definition-overriding=true

# Http Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# DDI authentication configuration
hawkbit.server.ddi.security.authentication.anonymous.enabled=false
hawkbit.server.ddi.security.authentication.targettoken.enabled=true
hawkbit.server.ddi.security.authentication.gatewaytoken.enabled=false
hawkbit.server.ddi.security.createTargetOnRun=false

# Optional events
hawkbit.server.repository.publish-target-poll-event=false

hawkbit.default.maxAssignments=999
spring.cloud.config.enabled=false

#PKI PrivateKey path
#Environment Specific:Needs update once available
cosmos.server.pki.internal.dd.private.keyPath=/CERTIFICATES/INTERNAL/DEV/DD/PRIVATEKEY

management.endpoints.jmx.exposure.include=info,loggers

# Rollout Scheduler
rollout.scheduler.enabled=true
rollout.valid.end.date.days=2
