/**
 * Copyright (c) 2015 Bosch Software Innovations GmbH and others.
 * <p>
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.eclipse.hawkbit.repository;

import org.eclipse.hawkbit.repository.model.DistributionSetType;
import org.eclipse.hawkbit.repository.model.SoftwareModuleType;

/**
 * Repository API constants.
 */
public final class Constants {

    /**
     * {@link SoftwareModuleType#getKey()} of a {@link SoftwareModuleType}
     * generated by repository for every new account for Firmware/Operating
     * System.
     */
    public static final String SMT_DEFAULT_OS_KEY = "os";

    /**
     * {@link SoftwareModuleType#getKey()} of a {@link SoftwareModuleType}
     * generated by repository for every new account for Firmware/Operating
     * System.
     */
    public static final String SMF_DEFAULT_OS_KEY = "qnx";


    /**
     * {@link SoftwareModuleType#getKey()} of a {@link SoftwareModuleType}
     * generated by repository for every new account for applications.
     */
    public static final String SMT_DEFAULT_APP_KEY = "application";


    public static final String SMT_CUSTOM_KEY = "Default";

    /**
     * {@link SoftwareModuleType#getName()} of a {@link SoftwareModuleType}
     * generated by repository for every new account for "Firmware/Operating
     * System" .
     */
    public static final String SMT_DEFAULT_OS_NAME = "OS";
    /**
     * {@link SoftwareModuleType#getName()} of a {@link SoftwareModuleType}
     * generated by repository for every new account for "applications/apps".
     */
    public static final String SMT_DEFAULT_APP_NAME = "Application";


    public static final String SMT_CUSTOM_APP_NAME = "Default";


    /**
     * {@link DistributionSetType#getKey()} of a {@link DistributionSetType}
     * generated by repository for every new account that includes
     * {@link #SMT_DEFAULT_OS_KEY} as mandatory module and optional
     * {@link #SMT_DEFAULT_APP_KEY}s.
     */
    public static final String DST_DEFAULT_OS_WITH_APPS_KEY = "os_app";


    public static final String DST_CUSTOM_KEY = "Default";


    /**
     * {@link DistributionSetType#getName()} of a {@link DistributionSetType}
     * generated by repository for every new account that includes
     * {@link #SMT_DEFAULT_OS_KEY} as mandatory module and optional
     * {@link #SMT_DEFAULT_APP_KEY}s.
     */
    public static final String DST_DEFAULT_OS_WITH_APPS_NAME = "OS with app(s)";

    public static final String DST_CUSTOM_NAME = "Default";


    /**
     * {@link DistributionSetType#getKey()} of a {@link DistributionSetType}
     * generated by repository for every new account that includes only
     * {@link #SMT_DEFAULT_OS_KEY} as mandatory module.
     */
    public static final String DST_DEFAULT_OS_ONLY_KEY = "os";

    /**
     * {@link DistributionSetType#getName()} of a {@link DistributionSetType}
     * generated by repository for every new account that includes only
     * {@link #SMT_DEFAULT_OS_KEY} as mandatory module.
     */
    public static final String DST_DEFAULT_OS_ONLY_NAME = "OS only";

    /**
     * {@link DistributionSetType#getKey()} of a {@link DistributionSetType}
     * generated by repository for every new account that includes only
     * {@link #SMT_DEFAULT_APP_KEY} as mandatory module.
     */
    public static final String DST_DEFAULT_APP_ONLY_KEY = "app";

    /**
     * {@link DistributionSetType#getName()} of a {@link DistributionSetType}
     * generated by repository for every new account that includes only
     * {@link #SMT_DEFAULT_APP_KEY} as mandatory module.
     */
    public static final String DST_DEFAULT_APP_ONLY_NAME = "App(s) only";

    public static final Integer MAX_ASSIGNMENTS_DEFAULT = 999;

    /**
     * Maximum number of retry attempts.
     */
    public static final int TX_RT_MAX = 10;

    /**
     * Delay value for retry operations in milliseconds.
     */
    public static final long TX_RT_DELAY = 100;

    private Constants() {
        // Utility class.
    }
}
